using System.Diagnostics;
using Offstream.Core.Encoding;
using Offstream.Core.Metadata;
using Xunit;

namespace Offstream.Core.Tests.Encoding;

/// <summary>
/// A scratch directory plus the inputs the encode integration suites need: a real WAV and a
/// real JPEG, both generated by ffmpeg so no binary fixtures live in the repository.
/// </summary>
internal sealed class EncodeWorkspace : IDisposable
{
    private readonly string _root = Path.Combine(
        Path.GetTempPath(), $"offstream-encode-{Guid.NewGuid():N}");

    public EncodeWorkspace() => Directory.CreateDirectory(_root);

    /// <summary>ffmpeg resolved from <c>PATH</c>, as CI and the developer machine both provide it.</summary>
    public FFmpegRunner Runner { get; } = new("ffmpeg");

    /// <summary>A path inside the scratch directory. The file need not exist.</summary>
    public string PathTo(string fileName) => Path.Combine(_root, fileName);

    /// <summary>A path for <paramref name="format"/>'s natural extension.</summary>
    public string PathFor(MediaFormat format, string stem = "out") =>
        PathTo($"{stem}.{EncodingProfiles.For(format).Extension}");

    /// <summary>Generates a two-second 440 Hz tone to encode from.</summary>
    public async Task<string> CreateSourceWavAsync(string name = "source.wav")
    {
        var path = PathTo(name);

        await Runner.RunOrThrowAsync(
            ["-hide_banner", "-nostdin", "-y", "-f", "lavfi", "-i", "sine=frequency=440:duration=2", path],
            TimeSpan.FromSeconds(30));

        Assert.True(File.Exists(path));
        return path;
    }

    /// <summary>Generates a small solid-colour JPEG to embed as cover art.</summary>
    public async Task<string> CreateCoverArtAsync(string name = "cover.jpg")
    {
        var path = PathTo(name);

        await Runner.RunOrThrowAsync(
            ["-hide_banner", "-nostdin", "-y", "-f", "lavfi", "-i", "color=c=red:s=120x120",
                "-frames:v", "1", path],
            TimeSpan.FromSeconds(30));

        Assert.True(new FileInfo(path).Length > 0);
        return path;
    }

    public void Dispose()
    {
        try
        {
            Directory.Delete(_root, recursive: true);
        }
        catch (IOException)
        {
            // A file still held open is not worth failing a test over.
        }
    }
}

/// <summary>Thin ffprobe wrapper: the suites assert on what ffprobe reports, not on ffmpeg's word.</summary>
internal static class FFprobe
{
    /// <summary>Runs ffprobe and returns stdout.</summary>
    public static async Task<string> QueryAsync(params string[] arguments)
    {
        var startInfo = new ProcessStartInfo
        {
            FileName = "ffprobe",
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            CreateNoWindow = true,
        };

        foreach (var argument in arguments) startInfo.ArgumentList.Add(argument);

        using var process = Process.Start(startInfo);
        Assert.NotNull(process);

        var stdout = process.StandardOutput.ReadToEndAsync();
        var stderr = process.StandardError.ReadToEndAsync();

        await process.WaitForExitAsync();
        _ = await stderr;

        return await stdout;
    }

    /// <summary>Everything ffprobe knows about the video streams, which is where a picture lands.</summary>
    public static Task<string> VideoStreamsAsync(string path) =>
        QueryAsync(
            "-v", "error", "-select_streams", "v",
            "-show_entries", "stream=codec_name:stream_disposition=attached_pic",
            "-of", "default=noprint_wrappers=1", path);

    /// <summary>Container-level tags.</summary>
    public static Task<string> FormatTagsAsync(string path) =>
        QueryAsync("-v", "error", "-show_entries", "format_tags", "-of", "default=noprint_wrappers=1", path);

    /// <summary>Tags on the first audio stream — where Ogg keeps them (§5.2).</summary>
    public static Task<string> AudioStreamTagsAsync(string path) =>
        QueryAsync(
            "-v", "error", "-select_streams", "a:0",
            "-show_entries", "stream_tags", "-of", "default=noprint_wrappers=1", path);
}
