<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Offstream.Core.Tests</RootNamespace>
    <AssemblyName>Offstream.Core.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Offstream.Core\Offstream.Core.csproj" />
    <ProjectReference Include="..\..\src\Offstream.App\Offstream.App.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Moq" />
    <PackageReference Include="System.IO.Abstractions.TestingHelpers" />
  </ItemGroup>

</Project>
